name: ADF and Databricks CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-databricks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Databricks CLI
      run: |
        echo "Installing Databricks CLI"
        pip install databricks-cli
    - name: Configure Databricks CLI
      run: |
        echo "Configuring Databricks CLI"
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = https://adb-2081951158852644.4.azuredatabricks.net" >> ~/.databrickscfg
        echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databrickscfg
    - name: Deploy Databricks Notebooks
      run: |
        echo "Starting Databricks deployment to /carbo-loading-UAT"
        for file in "Databricks Notebooks"/*; do
          if [[ "$file" == *.ipynb ]]; then
            echo "Deploying $file to /carbo-loading-UAT/$(basename "$file")"
            databricks workspace import --format JUPYTER --overwrite "$file" "/carbo-loading-UAT/$(basename "$file")" || echo "Failed to deploy $file"
          elif [[ "$file" == *.py ]]; then
            echo "Deploying $file to /carbo-loading-UAT/$(basename "$file")"
            databricks workspace import --format SOURCE --overwrite "$file" "/carbo-loading-UAT/$(basename "$file")" || echo "Failed to deploy $file"
          else
            echo "Skipping $file - unsupported extension"
          fi
        done
        echo "Databricks deployment completed"
  deploy-adf:
    runs-on: ubuntu-latest
    needs: deploy-databricks
    steps:
    - uses: actions/checkout@v3
      with:
        ref: adf_publish
    - name: Install Azure CLI
      run: |
        echo "Installing Azure CLI"
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Login to Azure
      run: |
        echo "Logging into Azure"
        az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}" --output none
    - name: Deploy ADF
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 2da1eaa1-70c6-4d3c-8534-816bf3f969e2
        resourceGroupName: rg-carbo
        template: ./adf-carbo/ARMTemplateForFactory.json
        parameters: ./adf-carbo/ARMTemplateParametersForFactory.json
        deploymentMode: Incremental
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
