name: ADF and Databricks CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-databricks:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'Databricks Notebooks/') || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Databricks Notebooks
      run: |
        echo "Starting Databricks deployment to Workspace/carbo-loading-UAT"
        for file in "Databricks Notebooks"/*; do
          echo "Deploying $file to Workspace/carbo-loading-UAT/$(basename "$file")"
          curl -n -X POST https://${{ secrets.DATABRICKS_HOST }}/api/2.0/workspace/import \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -F "path=/carbo-loading-UAT/$(basename "$file")" \
            -F "format=SOURCE" \
            -F "content=$(base64 "$file")"
        done
        echo "Databricks deployment completed"
  deploy-adf:
      runs-on: ubuntu-latest
      needs: deploy-databricks
      if: always() || contains(github.event.head_commit.modified, 'adf-carbo/') || github.event_name == 'workflow_dispatch'
      steps:
      - uses: actions/checkout@v3
        with:
          ref: adf_publish
      - name: Echo ADF Deployment Start
        run: |
          echo "Starting ADF deployment to adf-carbo-uat"
          echo "Deploying ARM template from adf-carbo/ARMTemplateForFactory.json"
      - name: Deploy ADF
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-carbo
          template: ./adf-carbo/ARMTemplateForFactory.json
          parameters: 'factoryName=adf-carbo-uat'
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Echo ADF Deployment Complete
        run: |
          echo "ADF deployment completed"
