name: ADF and Databricks CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-databricks:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'Databricks Notebooks/') || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Databricks Notebooks
      run: |
        echo "Starting Databricks deployment to /carbo-loading-UAT"
        for file in "Databricks Notebooks"/*; do
          echo "Deploying $file to /carbo-loading-UAT/$(basename "$file")"
          curl -n -X POST https://${{ secrets.DATABRICKS_HOST }}/api/2.0/workspace/import \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -F "path=/carbo-loading-UAT/$(basename "$file")" \
            -F "format=SOURCE" \
            -F "content=$(base64 "$file")"
        done
        echo "Databricks deployment completed"
  deploy-adf:
    runs-on: ubuntu-latest
    needs: deploy-databricks
    if: always() || contains(github.event.head_commit.modified, 'adf-carbo/') || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: adf_publish
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Debug Azure Context
      run: |
        echo "Client ID: $(echo $AZURE_CREDENTIALS | jq -r '.clientId')"
        echo "Client Secret: $(echo $AZURE_CREDENTIALS | jq -r '.clientSecret')"
        echo "Tenant ID: $(echo $AZURE_CREDENTIALS | jq -r '.tenantId')"
        echo "Subscription ID: $(echo $AZURE_CREDENTIALS | jq -r '.subscriptionId')"
        echo "Resource Group: rg-carbo"
    - name: Echo ADF Deployment Start
      run: |
        echo "Starting ADF deployment to adf-carbo-uat"
        echo "Deploying ARM template from adf-carbo/ARMTemplateForFactory.json"
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Login to Azure
      run: |
        echo "Logging into Azure with service principal"
        az login --service-principal -u "$(echo $AZURE_CREDENTIALS | jq -r '.clientId')" -p "$(echo $AZURE_CREDENTIALS | jq -r '.clientSecret')" --tenant "$(echo $AZURE_CREDENTIALS | jq -r '.tenantId')"
    - name: Deploy ADF with az cli
      run: |
        echo "Running ARM deployment"
        az deployment group create --resource-group rg-carbo --template-file ./adf-carbo/ARMTemplateForFactory.json --parameters factoryName=adf-carbo-uat --subscription 2da1eaa1-70c6-4d3c-8534-816bf3f969e2
        echo "ARM deployment completed"
    - name: Echo ADF Deployment Complete
      run: |
        echo "ADF deployment completed"
